// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: events.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

// SlotStatus message definition for slot information
type SlotStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slot          uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Parent        uint64                 `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	BlockHeight   uint64                 `protobuf:"varint,5,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotStatus) Reset() {
	*x = SlotStatus{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotStatus) ProtoMessage() {}

func (x *SlotStatus) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotStatus.ProtoReflect.Descriptor instead.
func (*SlotStatus) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *SlotStatus) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SlotStatus) GetParent() uint64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *SlotStatus) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SlotStatus) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *SlotStatus) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

// This message matches the Yellowstone scheme, with slot kept as enum at field #9.
type SubscribeUpdateAccountInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        []byte                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Lamports      uint64                 `protobuf:"varint,2,opt,name=lamports,proto3" json:"lamports,omitempty"`
	Owner         []byte                 `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Executable    bool                   `protobuf:"varint,4,opt,name=executable,proto3" json:"executable,omitempty"`
	RentEpoch     uint64                 `protobuf:"varint,5,opt,name=rent_epoch,json=rentEpoch,proto3" json:"rent_epoch,omitempty"`
	Data          []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	WriteVersion  uint64                 `protobuf:"varint,7,opt,name=write_version,json=writeVersion,proto3" json:"write_version,omitempty"`
	TxnSignature  []byte                 `protobuf:"bytes,8,opt,name=txn_signature,json=txnSignature,proto3,oneof" json:"txn_signature,omitempty"`
	Slot          *SlotStatus            `protobuf:"bytes,9,opt,name=slot,proto3,oneof" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeUpdateAccountInfo) Reset() {
	*x = SubscribeUpdateAccountInfo{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeUpdateAccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeUpdateAccountInfo) ProtoMessage() {}

func (x *SubscribeUpdateAccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeUpdateAccountInfo.ProtoReflect.Descriptor instead.
func (*SubscribeUpdateAccountInfo) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeUpdateAccountInfo) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *SubscribeUpdateAccountInfo) GetLamports() uint64 {
	if x != nil {
		return x.Lamports
	}
	return 0
}

func (x *SubscribeUpdateAccountInfo) GetOwner() []byte {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *SubscribeUpdateAccountInfo) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

func (x *SubscribeUpdateAccountInfo) GetRentEpoch() uint64 {
	if x != nil {
		return x.RentEpoch
	}
	return 0
}

func (x *SubscribeUpdateAccountInfo) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SubscribeUpdateAccountInfo) GetWriteVersion() uint64 {
	if x != nil {
		return x.WriteVersion
	}
	return 0
}

func (x *SubscribeUpdateAccountInfo) GetTxnSignature() []byte {
	if x != nil {
		return x.TxnSignature
	}
	return nil
}

func (x *SubscribeUpdateAccountInfo) GetSlot() *SlotStatus {
	if x != nil {
		return x.Slot
	}
	return nil
}

type SlotStatusEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fixed length fields grouped
	Slot          uint64 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`                                  // 8 bytes, frequently accessed
	Parent        uint64 `protobuf:"varint,2,opt,name=parent,proto3" json:"parent,omitempty"`                              // 8 bytes
	Status        int32  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                              // enum (4 bytes)
	BlockHash     []byte `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`        // 32-byte block hash
	BlockHeight   uint64 `protobuf:"varint,5,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"` // block height
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotStatusEvent) Reset() {
	*x = SlotStatusEvent{}
	mi := &file_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotStatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotStatusEvent) ProtoMessage() {}

func (x *SlotStatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotStatusEvent.ProtoReflect.Descriptor instead.
func (*SlotStatusEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{3}
}

func (x *SlotStatusEvent) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *SlotStatusEvent) GetParent() uint64 {
	if x != nil {
		return x.Parent
	}
	return 0
}

func (x *SlotStatusEvent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SlotStatusEvent) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *SlotStatusEvent) GetBlockHeight() uint64 {
	if x != nil {
		return x.BlockHeight
	}
	return 0
}

type MessageHeader struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Group small fixed-size fields together
	NumRequiredSignatures       uint32 `protobuf:"varint,1,opt,name=num_required_signatures,json=numRequiredSignatures,proto3" json:"num_required_signatures,omitempty"`
	NumReadonlySignedAccounts   uint32 `protobuf:"varint,2,opt,name=num_readonly_signed_accounts,json=numReadonlySignedAccounts,proto3" json:"num_readonly_signed_accounts,omitempty"`
	NumReadonlyUnsignedAccounts uint32 `protobuf:"varint,3,opt,name=num_readonly_unsigned_accounts,json=numReadonlyUnsignedAccounts,proto3" json:"num_readonly_unsigned_accounts,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *MessageHeader) Reset() {
	*x = MessageHeader{}
	mi := &file_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageHeader) ProtoMessage() {}

func (x *MessageHeader) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageHeader.ProtoReflect.Descriptor instead.
func (*MessageHeader) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{4}
}

func (x *MessageHeader) GetNumRequiredSignatures() uint32 {
	if x != nil {
		return x.NumRequiredSignatures
	}
	return 0
}

func (x *MessageHeader) GetNumReadonlySignedAccounts() uint32 {
	if x != nil {
		return x.NumReadonlySignedAccounts
	}
	return 0
}

func (x *MessageHeader) GetNumReadonlyUnsignedAccounts() uint32 {
	if x != nil {
		return x.NumReadonlyUnsignedAccounts
	}
	return 0
}

type CompiledInstruction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProgramIdIndex uint32                 `protobuf:"varint,1,opt,name=program_id_index,json=programIdIndex,proto3" json:"program_id_index,omitempty"`
	Data           []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                 // Variable length after fixed
	Accounts       []uint32               `protobuf:"varint,3,rep,packed,name=accounts,proto3" json:"accounts,omitempty"` // Use packed for better encoding
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CompiledInstruction) Reset() {
	*x = CompiledInstruction{}
	mi := &file_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompiledInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompiledInstruction) ProtoMessage() {}

func (x *CompiledInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompiledInstruction.ProtoReflect.Descriptor instead.
func (*CompiledInstruction) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{5}
}

func (x *CompiledInstruction) GetProgramIdIndex() uint32 {
	if x != nil {
		return x.ProgramIdIndex
	}
	return 0
}

func (x *CompiledInstruction) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CompiledInstruction) GetAccounts() []uint32 {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type LoadedAddresses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Writable      [][]byte               `protobuf:"bytes,1,rep,name=writable,proto3" json:"writable,omitempty"`
	Readonly      [][]byte               `protobuf:"bytes,2,rep,name=readonly,proto3" json:"readonly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadedAddresses) Reset() {
	*x = LoadedAddresses{}
	mi := &file_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadedAddresses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadedAddresses) ProtoMessage() {}

func (x *LoadedAddresses) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadedAddresses.ProtoReflect.Descriptor instead.
func (*LoadedAddresses) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{6}
}

func (x *LoadedAddresses) GetWritable() [][]byte {
	if x != nil {
		return x.Writable
	}
	return nil
}

func (x *LoadedAddresses) GetReadonly() [][]byte {
	if x != nil {
		return x.Readonly
	}
	return nil
}

type MessageAddressTableLookup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountKey      []byte                 `protobuf:"bytes,1,opt,name=account_key,json=accountKey,proto3" json:"account_key,omitempty"`                // 32 bytes
	WritableIndexes []byte                 `protobuf:"bytes,2,opt,name=writable_indexes,json=writableIndexes,proto3" json:"writable_indexes,omitempty"` // 32 bytes
	ReadonlyIndexes []byte                 `protobuf:"bytes,3,opt,name=readonly_indexes,json=readonlyIndexes,proto3" json:"readonly_indexes,omitempty"` // 32 bytes
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessageAddressTableLookup) Reset() {
	*x = MessageAddressTableLookup{}
	mi := &file_events_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageAddressTableLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageAddressTableLookup) ProtoMessage() {}

func (x *MessageAddressTableLookup) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageAddressTableLookup.ProtoReflect.Descriptor instead.
func (*MessageAddressTableLookup) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{7}
}

func (x *MessageAddressTableLookup) GetAccountKey() []byte {
	if x != nil {
		return x.AccountKey
	}
	return nil
}

func (x *MessageAddressTableLookup) GetWritableIndexes() []byte {
	if x != nil {
		return x.WritableIndexes
	}
	return nil
}

func (x *MessageAddressTableLookup) GetReadonlyIndexes() []byte {
	if x != nil {
		return x.ReadonlyIndexes
	}
	return nil
}

// Unified Message structure that handles both Legacy and v0
type Message struct {
	state               protoimpl.MessageState       `protogen:"open.v1"`
	Version             uint32                       `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"` // 0 for legacy, 1 for v0
	Header              *MessageHeader               `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	RecentBlockHash     []byte                       `protobuf:"bytes,3,opt,name=recent_block_hash,json=recentBlockHash,proto3" json:"recent_block_hash,omitempty"` // 32 bytes
	AccountKeys         [][]byte                     `protobuf:"bytes,4,rep,name=account_keys,json=accountKeys,proto3" json:"account_keys,omitempty"`               // Array of 32 byte keys
	Instructions        []*CompiledInstruction       `protobuf:"bytes,5,rep,name=instructions,proto3" json:"instructions,omitempty"`
	AddressTableLookups []*MessageAddressTableLookup `protobuf:"bytes,6,rep,name=address_table_lookups,json=addressTableLookups,proto3" json:"address_table_lookups,omitempty"` // Only used for v0
	LoadedAddresses     *LoadedAddresses             `protobuf:"bytes,7,opt,name=loaded_addresses,json=loadedAddresses,proto3" json:"loaded_addresses,omitempty"`               // Only used for v0
	IsWritable          []bool                       `protobuf:"varint,8,rep,packed,name=is_writable,json=isWritable,proto3" json:"is_writable,omitempty"`                      // Account write permissions
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_events_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{8}
}

func (x *Message) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Message) GetHeader() *MessageHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Message) GetRecentBlockHash() []byte {
	if x != nil {
		return x.RecentBlockHash
	}
	return nil
}

func (x *Message) GetAccountKeys() [][]byte {
	if x != nil {
		return x.AccountKeys
	}
	return nil
}

func (x *Message) GetInstructions() []*CompiledInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *Message) GetAddressTableLookups() []*MessageAddressTableLookup {
	if x != nil {
		return x.AddressTableLookups
	}
	return nil
}

func (x *Message) GetLoadedAddresses() *LoadedAddresses {
	if x != nil {
		return x.LoadedAddresses
	}
	return nil
}

func (x *Message) GetIsWritable() []bool {
	if x != nil {
		return x.IsWritable
	}
	return nil
}

type SanitizedTransaction struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Message                 *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MessageHash             []byte                 `protobuf:"bytes,2,opt,name=message_hash,json=messageHash,proto3" json:"message_hash,omitempty"` // 32 bytes
	Signatures              [][]byte               `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`                      // Array of 64 byte signatures
	IsSimpleVoteTransaction bool                   `protobuf:"varint,4,opt,name=is_simple_vote_transaction,json=isSimpleVoteTransaction,proto3" json:"is_simple_vote_transaction,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SanitizedTransaction) Reset() {
	*x = SanitizedTransaction{}
	mi := &file_events_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SanitizedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SanitizedTransaction) ProtoMessage() {}

func (x *SanitizedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SanitizedTransaction.ProtoReflect.Descriptor instead.
func (*SanitizedTransaction) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{9}
}

func (x *SanitizedTransaction) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *SanitizedTransaction) GetMessageHash() []byte {
	if x != nil {
		return x.MessageHash
	}
	return nil
}

func (x *SanitizedTransaction) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *SanitizedTransaction) GetIsSimpleVoteTransaction() bool {
	if x != nil {
		return x.IsSimpleVoteTransaction
	}
	return false
}

type TransactionEvent struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Slot                  uint64                 `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Signature             []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // 64 bytes
	Index                 uint64                 `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	IsVote                bool                   `protobuf:"varint,4,opt,name=is_vote,json=isVote,proto3" json:"is_vote,omitempty"`
	Transaction           *SanitizedTransaction  `protobuf:"bytes,5,opt,name=transaction,proto3" json:"transaction,omitempty"`
	TransactionStatusMeta *TransactionStatusMeta `protobuf:"bytes,6,opt,name=transaction_status_meta,json=transactionStatusMeta,proto3" json:"transaction_status_meta,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TransactionEvent) Reset() {
	*x = TransactionEvent{}
	mi := &file_events_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionEvent) ProtoMessage() {}

func (x *TransactionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionEvent.ProtoReflect.Descriptor instead.
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{10}
}

func (x *TransactionEvent) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *TransactionEvent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TransactionEvent) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TransactionEvent) GetIsVote() bool {
	if x != nil {
		return x.IsVote
	}
	return false
}

func (x *TransactionEvent) GetTransaction() *SanitizedTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *TransactionEvent) GetTransactionStatusMeta() *TransactionStatusMeta {
	if x != nil {
		return x.TransactionStatusMeta
	}
	return nil
}

type InnerInstruction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruction   *CompiledInstruction   `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	StackHeight   *uint32                `protobuf:"varint,2,opt,name=stack_height,json=stackHeight,proto3,oneof" json:"stack_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerInstruction) Reset() {
	*x = InnerInstruction{}
	mi := &file_events_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerInstruction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerInstruction) ProtoMessage() {}

func (x *InnerInstruction) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerInstruction.ProtoReflect.Descriptor instead.
func (*InnerInstruction) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{11}
}

func (x *InnerInstruction) GetInstruction() *CompiledInstruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

func (x *InnerInstruction) GetStackHeight() uint32 {
	if x != nil && x.StackHeight != nil {
		return *x.StackHeight
	}
	return 0
}

type InnerInstructions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Instructions  []*InnerInstruction    `protobuf:"bytes,2,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InnerInstructions) Reset() {
	*x = InnerInstructions{}
	mi := &file_events_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InnerInstructions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerInstructions) ProtoMessage() {}

func (x *InnerInstructions) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerInstructions.ProtoReflect.Descriptor instead.
func (*InnerInstructions) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{12}
}

func (x *InnerInstructions) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *InnerInstructions) GetInstructions() []*InnerInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

type UiTokenAmount struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UiAmount       float64                `protobuf:"fixed64,1,opt,name=ui_amount,json=uiAmount,proto3" json:"ui_amount,omitempty"`
	Decimals       uint32                 `protobuf:"varint,2,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Amount         string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	UiAmountString string                 `protobuf:"bytes,4,opt,name=ui_amount_string,json=uiAmountString,proto3" json:"ui_amount_string,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UiTokenAmount) Reset() {
	*x = UiTokenAmount{}
	mi := &file_events_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UiTokenAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UiTokenAmount) ProtoMessage() {}

func (x *UiTokenAmount) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UiTokenAmount.ProtoReflect.Descriptor instead.
func (*UiTokenAmount) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{13}
}

func (x *UiTokenAmount) GetUiAmount() float64 {
	if x != nil {
		return x.UiAmount
	}
	return 0
}

func (x *UiTokenAmount) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *UiTokenAmount) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *UiTokenAmount) GetUiAmountString() string {
	if x != nil {
		return x.UiAmountString
	}
	return ""
}

type TransactionTokenBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIndex  uint32                 `protobuf:"varint,1,opt,name=account_index,json=accountIndex,proto3" json:"account_index,omitempty"`
	Mint          string                 `protobuf:"bytes,2,opt,name=mint,proto3" json:"mint,omitempty"`
	UiTokenAmount *UiTokenAmount         `protobuf:"bytes,3,opt,name=ui_token_amount,json=uiTokenAmount,proto3" json:"ui_token_amount,omitempty"`
	Owner         string                 `protobuf:"bytes,4,opt,name=owner,proto3" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionTokenBalance) Reset() {
	*x = TransactionTokenBalance{}
	mi := &file_events_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionTokenBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionTokenBalance) ProtoMessage() {}

func (x *TransactionTokenBalance) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionTokenBalance.ProtoReflect.Descriptor instead.
func (*TransactionTokenBalance) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{14}
}

func (x *TransactionTokenBalance) GetAccountIndex() uint32 {
	if x != nil {
		return x.AccountIndex
	}
	return 0
}

func (x *TransactionTokenBalance) GetMint() string {
	if x != nil {
		return x.Mint
	}
	return ""
}

func (x *TransactionTokenBalance) GetUiTokenAmount() *UiTokenAmount {
	if x != nil {
		return x.UiTokenAmount
	}
	return nil
}

func (x *TransactionTokenBalance) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

type Reward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pubkey        string                 `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Lamports      int64                  `protobuf:"varint,2,opt,name=lamports,proto3" json:"lamports,omitempty"`
	PostBalance   uint64                 `protobuf:"varint,3,opt,name=post_balance,json=postBalance,proto3" json:"post_balance,omitempty"`
	RewardType    int32                  `protobuf:"varint,4,opt,name=reward_type,json=rewardType,proto3" json:"reward_type,omitempty"`
	Commission    uint32                 `protobuf:"varint,5,opt,name=commission,proto3" json:"commission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reward) Reset() {
	*x = Reward{}
	mi := &file_events_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reward) ProtoMessage() {}

func (x *Reward) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reward.ProtoReflect.Descriptor instead.
func (*Reward) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{15}
}

func (x *Reward) GetPubkey() string {
	if x != nil {
		return x.Pubkey
	}
	return ""
}

func (x *Reward) GetLamports() int64 {
	if x != nil {
		return x.Lamports
	}
	return 0
}

func (x *Reward) GetPostBalance() uint64 {
	if x != nil {
		return x.PostBalance
	}
	return 0
}

func (x *Reward) GetRewardType() int32 {
	if x != nil {
		return x.RewardType
	}
	return 0
}

func (x *Reward) GetCommission() uint32 {
	if x != nil {
		return x.Commission
	}
	return 0
}

type TransactionStatusMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Most frequently accessed fields first
	IsStatusErr  bool     `protobuf:"varint,1,opt,name=is_status_err,json=isStatusErr,proto3" json:"is_status_err,omitempty"`
	Fee          uint64   `protobuf:"varint,2,opt,name=fee,proto3" json:"fee,omitempty"`
	PreBalances  []uint64 `protobuf:"varint,3,rep,packed,name=pre_balances,json=preBalances,proto3" json:"pre_balances,omitempty"`
	PostBalances []uint64 `protobuf:"varint,4,rep,packed,name=post_balances,json=postBalances,proto3" json:"post_balances,omitempty"`
	// Larger and optional fields after
	InnerInstructions []*InnerInstructions       `protobuf:"bytes,5,rep,name=inner_instructions,json=innerInstructions,proto3" json:"inner_instructions,omitempty"`
	LogMessages       []string                   `protobuf:"bytes,6,rep,name=log_messages,json=logMessages,proto3" json:"log_messages,omitempty"`
	PreTokenBalances  []*TransactionTokenBalance `protobuf:"bytes,7,rep,name=pre_token_balances,json=preTokenBalances,proto3" json:"pre_token_balances,omitempty"`
	PostTokenBalances []*TransactionTokenBalance `protobuf:"bytes,8,rep,name=post_token_balances,json=postTokenBalances,proto3" json:"post_token_balances,omitempty"`
	Rewards           []*Reward                  `protobuf:"bytes,9,rep,name=rewards,proto3" json:"rewards,omitempty"`
	ErrorInfo         string                     `protobuf:"bytes,10,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionStatusMeta) Reset() {
	*x = TransactionStatusMeta{}
	mi := &file_events_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionStatusMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionStatusMeta) ProtoMessage() {}

func (x *TransactionStatusMeta) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionStatusMeta.ProtoReflect.Descriptor instead.
func (*TransactionStatusMeta) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{16}
}

func (x *TransactionStatusMeta) GetIsStatusErr() bool {
	if x != nil {
		return x.IsStatusErr
	}
	return false
}

func (x *TransactionStatusMeta) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

func (x *TransactionStatusMeta) GetPreBalances() []uint64 {
	if x != nil {
		return x.PreBalances
	}
	return nil
}

func (x *TransactionStatusMeta) GetPostBalances() []uint64 {
	if x != nil {
		return x.PostBalances
	}
	return nil
}

func (x *TransactionStatusMeta) GetInnerInstructions() []*InnerInstructions {
	if x != nil {
		return x.InnerInstructions
	}
	return nil
}

func (x *TransactionStatusMeta) GetLogMessages() []string {
	if x != nil {
		return x.LogMessages
	}
	return nil
}

func (x *TransactionStatusMeta) GetPreTokenBalances() []*TransactionTokenBalance {
	if x != nil {
		return x.PreTokenBalances
	}
	return nil
}

func (x *TransactionStatusMeta) GetPostTokenBalances() []*TransactionTokenBalance {
	if x != nil {
		return x.PostTokenBalances
	}
	return nil
}

func (x *TransactionStatusMeta) GetRewards() []*Reward {
	if x != nil {
		return x.Rewards
	}
	return nil
}

func (x *TransactionStatusMeta) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

// MessageWrapper is the top-level envelope for all event types
type MessageWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to EventMessage:
	//
	//	*MessageWrapper_AccountUpdate
	//	*MessageWrapper_Slot
	//	*MessageWrapper_Transaction
	EventMessage  isMessageWrapper_EventMessage `protobuf_oneof:"event_message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWrapper) Reset() {
	*x = MessageWrapper{}
	mi := &file_events_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWrapper) ProtoMessage() {}

func (x *MessageWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWrapper.ProtoReflect.Descriptor instead.
func (*MessageWrapper) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{17}
}

func (x *MessageWrapper) GetEventMessage() isMessageWrapper_EventMessage {
	if x != nil {
		return x.EventMessage
	}
	return nil
}

func (x *MessageWrapper) GetAccountUpdate() *SubscribeUpdateAccountInfo {
	if x != nil {
		if x, ok := x.EventMessage.(*MessageWrapper_AccountUpdate); ok {
			return x.AccountUpdate
		}
	}
	return nil
}

func (x *MessageWrapper) GetSlot() *SlotStatusEvent {
	if x != nil {
		if x, ok := x.EventMessage.(*MessageWrapper_Slot); ok {
			return x.Slot
		}
	}
	return nil
}

func (x *MessageWrapper) GetTransaction() *TransactionEvent {
	if x != nil {
		if x, ok := x.EventMessage.(*MessageWrapper_Transaction); ok {
			return x.Transaction
		}
	}
	return nil
}

type isMessageWrapper_EventMessage interface {
	isMessageWrapper_EventMessage()
}

type MessageWrapper_AccountUpdate struct {
	AccountUpdate *SubscribeUpdateAccountInfo `protobuf:"bytes,1,opt,name=account_update,json=accountUpdate,proto3,oneof"`
}

type MessageWrapper_Slot struct {
	Slot *SlotStatusEvent `protobuf:"bytes,2,opt,name=slot,proto3,oneof"`
}

type MessageWrapper_Transaction struct {
	Transaction *TransactionEvent `protobuf:"bytes,3,opt,name=transaction,proto3,oneof"`
}

func (*MessageWrapper_AccountUpdate) isMessageWrapper_EventMessage() {}

func (*MessageWrapper_Slot) isMessageWrapper_EventMessage() {}

func (*MessageWrapper_Transaction) isMessageWrapper_EventMessage() {}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\x13thor_streamer.types\"\a\n" +
	"\x05Empty\"\x92\x01\n" +
	"\n" +
	"SlotStatus\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\x04R\x06parent\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\fR\tblockHash\x12!\n" +
	"\fblock_height\x18\x05 \x01(\x04R\vblockHeight\"\xdd\x02\n" +
	"\x1aSubscribeUpdateAccountInfo\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\fR\x06pubkey\x12\x1a\n" +
	"\blamports\x18\x02 \x01(\x04R\blamports\x12\x14\n" +
	"\x05owner\x18\x03 \x01(\fR\x05owner\x12\x1e\n" +
	"\n" +
	"executable\x18\x04 \x01(\bR\n" +
	"executable\x12\x1d\n" +
	"\n" +
	"rent_epoch\x18\x05 \x01(\x04R\trentEpoch\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12#\n" +
	"\rwrite_version\x18\a \x01(\x04R\fwriteVersion\x12(\n" +
	"\rtxn_signature\x18\b \x01(\fH\x00R\ftxnSignature\x88\x01\x01\x128\n" +
	"\x04slot\x18\t \x01(\v2\x1f.thor_streamer.types.SlotStatusH\x01R\x04slot\x88\x01\x01B\x10\n" +
	"\x0e_txn_signatureB\a\n" +
	"\x05_slot\"\x97\x01\n" +
	"\x0fSlotStatusEvent\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x16\n" +
	"\x06parent\x18\x02 \x01(\x04R\x06parent\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\fR\tblockHash\x12!\n" +
	"\fblock_height\x18\x05 \x01(\x04R\vblockHeight\"\xcd\x01\n" +
	"\rMessageHeader\x126\n" +
	"\x17num_required_signatures\x18\x01 \x01(\rR\x15numRequiredSignatures\x12?\n" +
	"\x1cnum_readonly_signed_accounts\x18\x02 \x01(\rR\x19numReadonlySignedAccounts\x12C\n" +
	"\x1enum_readonly_unsigned_accounts\x18\x03 \x01(\rR\x1bnumReadonlyUnsignedAccounts\"s\n" +
	"\x13CompiledInstruction\x12(\n" +
	"\x10program_id_index\x18\x01 \x01(\rR\x0eprogramIdIndex\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1e\n" +
	"\baccounts\x18\x03 \x03(\rB\x02\x10\x01R\baccounts\"I\n" +
	"\x0fLoadedAddresses\x12\x1a\n" +
	"\bwritable\x18\x01 \x03(\fR\bwritable\x12\x1a\n" +
	"\breadonly\x18\x02 \x03(\fR\breadonly\"\x92\x01\n" +
	"\x19MessageAddressTableLookup\x12\x1f\n" +
	"\vaccount_key\x18\x01 \x01(\fR\n" +
	"accountKey\x12)\n" +
	"\x10writable_indexes\x18\x02 \x01(\fR\x0fwritableIndexes\x12)\n" +
	"\x10readonly_indexes\x18\x03 \x01(\fR\x0freadonlyIndexes\"\xd6\x03\n" +
	"\aMessage\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12:\n" +
	"\x06header\x18\x02 \x01(\v2\".thor_streamer.types.MessageHeaderR\x06header\x12*\n" +
	"\x11recent_block_hash\x18\x03 \x01(\fR\x0frecentBlockHash\x12!\n" +
	"\faccount_keys\x18\x04 \x03(\fR\vaccountKeys\x12L\n" +
	"\finstructions\x18\x05 \x03(\v2(.thor_streamer.types.CompiledInstructionR\finstructions\x12b\n" +
	"\x15address_table_lookups\x18\x06 \x03(\v2..thor_streamer.types.MessageAddressTableLookupR\x13addressTableLookups\x12O\n" +
	"\x10loaded_addresses\x18\a \x01(\v2$.thor_streamer.types.LoadedAddressesR\x0floadedAddresses\x12#\n" +
	"\vis_writable\x18\b \x03(\bB\x02\x10\x01R\n" +
	"isWritable\"\xce\x01\n" +
	"\x14SanitizedTransaction\x126\n" +
	"\amessage\x18\x01 \x01(\v2\x1c.thor_streamer.types.MessageR\amessage\x12!\n" +
	"\fmessage_hash\x18\x02 \x01(\fR\vmessageHash\x12\x1e\n" +
	"\n" +
	"signatures\x18\x03 \x03(\fR\n" +
	"signatures\x12;\n" +
	"\x1ais_simple_vote_transaction\x18\x04 \x01(\bR\x17isSimpleVoteTransaction\"\xa4\x02\n" +
	"\x10TransactionEvent\x12\x12\n" +
	"\x04slot\x18\x01 \x01(\x04R\x04slot\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x04R\x05index\x12\x17\n" +
	"\ais_vote\x18\x04 \x01(\bR\x06isVote\x12K\n" +
	"\vtransaction\x18\x05 \x01(\v2).thor_streamer.types.SanitizedTransactionR\vtransaction\x12b\n" +
	"\x17transaction_status_meta\x18\x06 \x01(\v2*.thor_streamer.types.TransactionStatusMetaR\x15transactionStatusMeta\"\x97\x01\n" +
	"\x10InnerInstruction\x12J\n" +
	"\vinstruction\x18\x01 \x01(\v2(.thor_streamer.types.CompiledInstructionR\vinstruction\x12&\n" +
	"\fstack_height\x18\x02 \x01(\rH\x00R\vstackHeight\x88\x01\x01B\x0f\n" +
	"\r_stack_height\"t\n" +
	"\x11InnerInstructions\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12I\n" +
	"\finstructions\x18\x02 \x03(\v2%.thor_streamer.types.InnerInstructionR\finstructions\"\x8a\x01\n" +
	"\rUiTokenAmount\x12\x1b\n" +
	"\tui_amount\x18\x01 \x01(\x01R\buiAmount\x12\x1a\n" +
	"\bdecimals\x18\x02 \x01(\rR\bdecimals\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12(\n" +
	"\x10ui_amount_string\x18\x04 \x01(\tR\x0euiAmountString\"\xb4\x01\n" +
	"\x17TransactionTokenBalance\x12#\n" +
	"\raccount_index\x18\x01 \x01(\rR\faccountIndex\x12\x12\n" +
	"\x04mint\x18\x02 \x01(\tR\x04mint\x12J\n" +
	"\x0fui_token_amount\x18\x03 \x01(\v2\".thor_streamer.types.UiTokenAmountR\ruiTokenAmount\x12\x14\n" +
	"\x05owner\x18\x04 \x01(\tR\x05owner\"\xa0\x01\n" +
	"\x06Reward\x12\x16\n" +
	"\x06pubkey\x18\x01 \x01(\tR\x06pubkey\x12\x1a\n" +
	"\blamports\x18\x02 \x01(\x03R\blamports\x12!\n" +
	"\fpost_balance\x18\x03 \x01(\x04R\vpostBalance\x12\x1f\n" +
	"\vreward_type\x18\x04 \x01(\x05R\n" +
	"rewardType\x12\x1e\n" +
	"\n" +
	"commission\x18\x05 \x01(\rR\n" +
	"commission\"\xa7\x04\n" +
	"\x15TransactionStatusMeta\x12\"\n" +
	"\ris_status_err\x18\x01 \x01(\bR\visStatusErr\x12\x10\n" +
	"\x03fee\x18\x02 \x01(\x04R\x03fee\x12%\n" +
	"\fpre_balances\x18\x03 \x03(\x04B\x02\x10\x01R\vpreBalances\x12'\n" +
	"\rpost_balances\x18\x04 \x03(\x04B\x02\x10\x01R\fpostBalances\x12U\n" +
	"\x12inner_instructions\x18\x05 \x03(\v2&.thor_streamer.types.InnerInstructionsR\x11innerInstructions\x12!\n" +
	"\flog_messages\x18\x06 \x03(\tR\vlogMessages\x12Z\n" +
	"\x12pre_token_balances\x18\a \x03(\v2,.thor_streamer.types.TransactionTokenBalanceR\x10preTokenBalances\x12\\\n" +
	"\x13post_token_balances\x18\b \x03(\v2,.thor_streamer.types.TransactionTokenBalanceR\x11postTokenBalances\x125\n" +
	"\arewards\x18\t \x03(\v2\x1b.thor_streamer.types.RewardR\arewards\x12\x1d\n" +
	"\n" +
	"error_info\x18\n" +
	" \x01(\tR\terrorInfo\"\x82\x02\n" +
	"\x0eMessageWrapper\x12X\n" +
	"\x0eaccount_update\x18\x01 \x01(\v2/.thor_streamer.types.SubscribeUpdateAccountInfoH\x00R\raccountUpdate\x12:\n" +
	"\x04slot\x18\x02 \x01(\v2$.thor_streamer.types.SlotStatusEventH\x00R\x04slot\x12I\n" +
	"\vtransaction\x18\x03 \x01(\v2%.thor_streamer.types.TransactionEventH\x00R\vtransactionB\x0f\n" +
	"\revent_message2b\n" +
	"\fThorStreamer\x12R\n" +
	"\rStreamUpdates\x12\x1a.thor_streamer.types.Empty\x1a#.thor_streamer.types.MessageWrapper0\x01B\x1bZ\x19thor_streamer/proto;protob\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_events_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: thor_streamer.types.Empty
	(*SlotStatus)(nil),                 // 1: thor_streamer.types.SlotStatus
	(*SubscribeUpdateAccountInfo)(nil), // 2: thor_streamer.types.SubscribeUpdateAccountInfo
	(*SlotStatusEvent)(nil),            // 3: thor_streamer.types.SlotStatusEvent
	(*MessageHeader)(nil),              // 4: thor_streamer.types.MessageHeader
	(*CompiledInstruction)(nil),        // 5: thor_streamer.types.CompiledInstruction
	(*LoadedAddresses)(nil),            // 6: thor_streamer.types.LoadedAddresses
	(*MessageAddressTableLookup)(nil),  // 7: thor_streamer.types.MessageAddressTableLookup
	(*Message)(nil),                    // 8: thor_streamer.types.Message
	(*SanitizedTransaction)(nil),       // 9: thor_streamer.types.SanitizedTransaction
	(*TransactionEvent)(nil),           // 10: thor_streamer.types.TransactionEvent
	(*InnerInstruction)(nil),           // 11: thor_streamer.types.InnerInstruction
	(*InnerInstructions)(nil),          // 12: thor_streamer.types.InnerInstructions
	(*UiTokenAmount)(nil),              // 13: thor_streamer.types.UiTokenAmount
	(*TransactionTokenBalance)(nil),    // 14: thor_streamer.types.TransactionTokenBalance
	(*Reward)(nil),                     // 15: thor_streamer.types.Reward
	(*TransactionStatusMeta)(nil),      // 16: thor_streamer.types.TransactionStatusMeta
	(*MessageWrapper)(nil),             // 17: thor_streamer.types.MessageWrapper
}
var file_events_proto_depIdxs = []int32{
	1,  // 0: thor_streamer.types.SubscribeUpdateAccountInfo.slot:type_name -> thor_streamer.types.SlotStatus
	4,  // 1: thor_streamer.types.Message.header:type_name -> thor_streamer.types.MessageHeader
	5,  // 2: thor_streamer.types.Message.instructions:type_name -> thor_streamer.types.CompiledInstruction
	7,  // 3: thor_streamer.types.Message.address_table_lookups:type_name -> thor_streamer.types.MessageAddressTableLookup
	6,  // 4: thor_streamer.types.Message.loaded_addresses:type_name -> thor_streamer.types.LoadedAddresses
	8,  // 5: thor_streamer.types.SanitizedTransaction.message:type_name -> thor_streamer.types.Message
	9,  // 6: thor_streamer.types.TransactionEvent.transaction:type_name -> thor_streamer.types.SanitizedTransaction
	16, // 7: thor_streamer.types.TransactionEvent.transaction_status_meta:type_name -> thor_streamer.types.TransactionStatusMeta
	5,  // 8: thor_streamer.types.InnerInstruction.instruction:type_name -> thor_streamer.types.CompiledInstruction
	11, // 9: thor_streamer.types.InnerInstructions.instructions:type_name -> thor_streamer.types.InnerInstruction
	13, // 10: thor_streamer.types.TransactionTokenBalance.ui_token_amount:type_name -> thor_streamer.types.UiTokenAmount
	12, // 11: thor_streamer.types.TransactionStatusMeta.inner_instructions:type_name -> thor_streamer.types.InnerInstructions
	14, // 12: thor_streamer.types.TransactionStatusMeta.pre_token_balances:type_name -> thor_streamer.types.TransactionTokenBalance
	14, // 13: thor_streamer.types.TransactionStatusMeta.post_token_balances:type_name -> thor_streamer.types.TransactionTokenBalance
	15, // 14: thor_streamer.types.TransactionStatusMeta.rewards:type_name -> thor_streamer.types.Reward
	2,  // 15: thor_streamer.types.MessageWrapper.account_update:type_name -> thor_streamer.types.SubscribeUpdateAccountInfo
	3,  // 16: thor_streamer.types.MessageWrapper.slot:type_name -> thor_streamer.types.SlotStatusEvent
	10, // 17: thor_streamer.types.MessageWrapper.transaction:type_name -> thor_streamer.types.TransactionEvent
	0,  // 18: thor_streamer.types.ThorStreamer.StreamUpdates:input_type -> thor_streamer.types.Empty
	17, // 19: thor_streamer.types.ThorStreamer.StreamUpdates:output_type -> thor_streamer.types.MessageWrapper
	19, // [19:20] is the sub-list for method output_type
	18, // [18:19] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_events_proto_msgTypes[2].OneofWrappers = []any{}
	file_events_proto_msgTypes[11].OneofWrappers = []any{}
	file_events_proto_msgTypes[17].OneofWrappers = []any{
		(*MessageWrapper_AccountUpdate)(nil),
		(*MessageWrapper_Slot)(nil),
		(*MessageWrapper_Transaction)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
