// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: publisher.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_publisher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_publisher_proto_rawDescGZIP(), []int{0}
}

func (x *StreamResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SubscribeAccountsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountAddress []string               `protobuf:"bytes,1,rep,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	OwnerAddress   []string               `protobuf:"bytes,2,rep,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"` // Filter by owner addresses
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeAccountsRequest) Reset() {
	*x = SubscribeAccountsRequest{}
	mi := &file_publisher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAccountsRequest) ProtoMessage() {}

func (x *SubscribeAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAccountsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeAccountsRequest) Descriptor() ([]byte, []int) {
	return file_publisher_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeAccountsRequest) GetAccountAddress() []string {
	if x != nil {
		return x.AccountAddress
	}
	return nil
}

func (x *SubscribeAccountsRequest) GetOwnerAddress() []string {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

var File_publisher_proto protoreflect.FileDescriptor

const file_publisher_proto_rawDesc = "" +
	"\n" +
	"\x0fpublisher.proto\x12\tpublisher\x1a\x1bgoogle/protobuf/empty.proto\"$\n" +
	"\x0eStreamResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"h\n" +
	"\x18SubscribeAccountsRequest\x12'\n" +
	"\x0faccount_address\x18\x01 \x03(\tR\x0eaccountAddress\x12#\n" +
	"\rowner_address\x18\x02 \x03(\tR\fownerAddress2\x93\x02\n" +
	"\x0eEventPublisher\x12P\n" +
	"\x17SubscribeToTransactions\x12\x16.google.protobuf.Empty\x1a\x19.publisher.StreamResponse\"\x000\x01\x12N\n" +
	"\x15SubscribeToSlotStatus\x12\x16.google.protobuf.Empty\x1a\x19.publisher.StreamResponse\"\x000\x01\x12_\n" +
	"\x19SubscribeToAccountUpdates\x12#.publisher.SubscribeAccountsRequest\x1a\x19.publisher.StreamResponse\"\x000\x01B\x15Z\x13thor_streamer/protob\x06proto3"

var (
	file_publisher_proto_rawDescOnce sync.Once
	file_publisher_proto_rawDescData []byte
)

func file_publisher_proto_rawDescGZIP() []byte {
	file_publisher_proto_rawDescOnce.Do(func() {
		file_publisher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_publisher_proto_rawDesc), len(file_publisher_proto_rawDesc)))
	})
	return file_publisher_proto_rawDescData
}

var file_publisher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_publisher_proto_goTypes = []any{
	(*StreamResponse)(nil),           // 0: publisher.StreamResponse
	(*SubscribeAccountsRequest)(nil), // 1: publisher.SubscribeAccountsRequest
	(*emptypb.Empty)(nil),            // 2: google.protobuf.Empty
}
var file_publisher_proto_depIdxs = []int32{
	2, // 0: publisher.EventPublisher.SubscribeToTransactions:input_type -> google.protobuf.Empty
	2, // 1: publisher.EventPublisher.SubscribeToSlotStatus:input_type -> google.protobuf.Empty
	1, // 2: publisher.EventPublisher.SubscribeToAccountUpdates:input_type -> publisher.SubscribeAccountsRequest
	0, // 3: publisher.EventPublisher.SubscribeToTransactions:output_type -> publisher.StreamResponse
	0, // 4: publisher.EventPublisher.SubscribeToSlotStatus:output_type -> publisher.StreamResponse
	0, // 5: publisher.EventPublisher.SubscribeToAccountUpdates:output_type -> publisher.StreamResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_publisher_proto_init() }
func file_publisher_proto_init() {
	if File_publisher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_publisher_proto_rawDesc), len(file_publisher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_publisher_proto_goTypes,
		DependencyIndexes: file_publisher_proto_depIdxs,
		MessageInfos:      file_publisher_proto_msgTypes,
	}.Build()
	File_publisher_proto = out.File
	file_publisher_proto_goTypes = nil
	file_publisher_proto_depIdxs = nil
}
